var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/Agreencup2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/grenade.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/Araisins4.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/paintbrush03.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/Atoy51.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/Atoyhelicopte.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/26427609.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/Aham6.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/26374158.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/AAIRPRES4.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AAIRPRES4.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26427609.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/22824840.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Apulley71.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASWANWHIT.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ANUTCRA10.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoy51.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Araisins4.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/grenade.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/paintbrush03.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/A_computerkey.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ADEEPFRYS.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABARPEAR.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aham6.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoyhelicopte.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agreencup2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/22911500.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ALITTERSC.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ALAUNHAMP.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26374158.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/22824840.thl.jpg",
    "stimulus/22911500.thl.jpg",
    "stimulus/26374158.thl.jpg",
    "stimulus/26427609.thl.jpg",
    "stimulus/AAIRPRES4.jpg",
    "stimulus/ABARPEAR.jpg",
    "stimulus/ADEEPFRYS.jpg",
    "stimulus/ALAUNHAMP.jpg",
    "stimulus/ALITTERSC.jpg",
    "stimulus/ANUTCRA10.jpg",
    "stimulus/ASWANWHIT.jpg",
    "stimulus/A_computerkey.jpg",
    "stimulus/Agreencup2.jpg",
    "stimulus/Aham6.jpg",
    "stimulus/Apulley71.jpg",
    "stimulus/Araisins4.jpg",
    "stimulus/Atoy51.jpg",
    "stimulus/Atoyhelicopte.jpg",
    "stimulus/grenade.jpg",
    "stimulus/paintbrush03.jpg",
];
