var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/AWOODENF3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/Anotepad9.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/Acampingknife.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/ShoeHorn.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/Azucchini9.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/26425323.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/APITCHE15.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/ARETRACT2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/fortune-cookie.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/26372690.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ShoeHorn.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ALAB36.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26370651.thm.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Ajacket12.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26372690.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABAGFLOU3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ADENTOOL.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoycoil.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/fortune-cookie.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26425323.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/APITCHE15.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWOODENF3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/DSCN6303-sm.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ANAPKHOL7.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abottleofwin4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acampingknife.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Anotepad9.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Azucchini9.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ARETRACT2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aflamingo4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 20},
];

var practice_images = [
    "stimulus/26370651.thm.jpg",
    "stimulus/26372690.thl.jpg",
    "stimulus/26425323.thl.jpg",
    "stimulus/ABAGFLOU3.jpg",
    "stimulus/ADENTOOL.jpg",
    "stimulus/ALAB36.jpg",
    "stimulus/ANAPKHOL7.jpg",
    "stimulus/APITCHE15.jpg",
    "stimulus/ARETRACT2.jpg",
    "stimulus/AWOODENF3.jpg",
    "stimulus/Abottleofwin4.jpg",
    "stimulus/Acampingknife.jpg",
    "stimulus/Aflamingo4.jpg",
    "stimulus/Ajacket12.jpg",
    "stimulus/Anotepad9.jpg",
    "stimulus/Atoycoil.jpg",
    "stimulus/Azucchini9.jpg",
    "stimulus/DSCN6303-sm.jpg",
    "stimulus/ShoeHorn.jpg",
    "stimulus/fortune-cookie.jpg",
];
