var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/26432755.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/APLANMOD2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/AORIGIRL3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/Acandycanesin.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/03015528000.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/hottub.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/Akitchenisla4.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/26370445.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/Apig5.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/Abeverageingl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acamera111.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABAKECON3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26370445.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/APLANMOD2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8021504.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AORIGIRL3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/hottub.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acandycanesin.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/APILL.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26394018.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26432755.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aclockradio4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agasblower2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/03015528000.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Apig5.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AHEADLIG9.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWEIGHTS8.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Akitchenisla4.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abeverageingl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/decorativesquash.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 20},
];

var practice_images = [
    "stimulus/03015528000.jpg",
    "stimulus/26370445.thl.jpg",
    "stimulus/26394018.thl.jpg",
    "stimulus/26432755.thl.jpg",
    "stimulus/8021504.thl.jpg",
    "stimulus/ABAKECON3.jpg",
    "stimulus/AHEADLIG9.jpg",
    "stimulus/AORIGIRL3.jpg",
    "stimulus/APILL.jpg",
    "stimulus/APLANMOD2.jpg",
    "stimulus/AWEIGHTS8.jpg",
    "stimulus/Abeverageingl.jpg",
    "stimulus/Acamera111.jpg",
    "stimulus/Acandycanesin.jpg",
    "stimulus/Aclockradio4.jpg",
    "stimulus/Agasblower2.jpg",
    "stimulus/Akitchenisla4.jpg",
    "stimulus/Apig5.jpg",
    "stimulus/decorativesquash.jpg",
    "stimulus/hottub.jpg",
];
