var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/ATRIANGL2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/Agarlicclove2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/ASALTPEPP.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/AARTBERRI.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/Agarbagebag.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/Adustpanbrus4.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/ASPOONS2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/fortune-cookie.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/ANECTARI3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/chocolatbox.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACLOGOPE3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABISHOP2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ADRUMSTI4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASPOONS2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Adustpanbrus4.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Ametalstool2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agarlicclove2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26421583.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Azebra8.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Astrawfan.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acomputerpro3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agarbagebag.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ATRIANGL2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/fortune-cookie.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Afeatherhat.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/chocolatbox.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/voguemagazine.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ANECTARI3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASALTPEPP.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AARTBERRI.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/26421583.thl.jpg",
    "stimulus/AARTBERRI.jpg",
    "stimulus/ABISHOP2.jpg",
    "stimulus/ACLOGOPE3.jpg",
    "stimulus/ADRUMSTI4.jpg",
    "stimulus/ANECTARI3.jpg",
    "stimulus/ASALTPEPP.jpg",
    "stimulus/ASPOONS2.jpg",
    "stimulus/ATRIANGL2.jpg",
    "stimulus/Acomputerpro3.jpg",
    "stimulus/Adustpanbrus4.jpg",
    "stimulus/Afeatherhat.jpg",
    "stimulus/Agarbagebag.jpg",
    "stimulus/Agarlicclove2.jpg",
    "stimulus/Ametalstool2.jpg",
    "stimulus/Astrawfan.jpg",
    "stimulus/Azebra8.jpg",
    "stimulus/chocolatbox.jpg",
    "stimulus/fortune-cookie.jpg",
    "stimulus/voguemagazine.jpg",
];
