var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/Aceramicjug10.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/Atray22.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/AANTSTOV6.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/26421357.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/26426803.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/AWASMACH.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/ANWSPAPER.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/22925228.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/31023139.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/ADOGSNACK.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aenvelope2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26426803.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABROWNBAG.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aceramicjug10.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AANTSTOV6.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ADOGSNACK.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASNOWSH11.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/31023139.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWASMACH.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Apairofrubbe3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26421357.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Apizzadoughin.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ANWSPAPER.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Chevypickup.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aonewaysign2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACLOWSTE5.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8020414.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/brownie.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/22925228.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atray22.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/22925228.thl.jpg",
    "stimulus/26421357.thl.jpg",
    "stimulus/26426803.thl.jpg",
    "stimulus/31023139.thl.jpg",
    "stimulus/8020414.thl.jpg",
    "stimulus/AANTSTOV6.jpg",
    "stimulus/ABROWNBAG.jpg",
    "stimulus/ACLOWSTE5.jpg",
    "stimulus/ADOGSNACK.jpg",
    "stimulus/ANWSPAPER.jpg",
    "stimulus/ASNOWSH11.jpg",
    "stimulus/AWASMACH.jpg",
    "stimulus/Aceramicjug10.jpg",
    "stimulus/Aenvelope2.jpg",
    "stimulus/Aonewaysign2.jpg",
    "stimulus/Apairofrubbe3.jpg",
    "stimulus/Apizzadoughin.jpg",
    "stimulus/Atray22.jpg",
    "stimulus/Chevypickup.jpg",
    "stimulus/brownie.jpg",
];
