var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/26384863.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/Aflatwoodenba.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/26432217.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/AHEADLI18.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/gingerbreadcookie.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/ACEDAR.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/26426317.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/AAIRGAUGE.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/ignitionkey01.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/Agreenplastic.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Afish57.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/babyswig.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACEDAR.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26432217.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aflatwoodenba.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aflowerpot9.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26424973.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26772987.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AAIRGAUGE.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AHEADLI18.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agreenplastic.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26426317.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26384863.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ALEGCAST3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ignitionkey01.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aashtray14.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASHOWCAP.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ANEWSBOX4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AELEMENT2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/gingerbreadcookie.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/26384863.thl.jpg",
    "stimulus/26424973.thl.jpg",
    "stimulus/26426317.thl.jpg",
    "stimulus/26432217.thl.jpg",
    "stimulus/26772987.thl.jpg",
    "stimulus/AAIRGAUGE.jpg",
    "stimulus/ACEDAR.jpg",
    "stimulus/AELEMENT2.jpg",
    "stimulus/AHEADLI18.jpg",
    "stimulus/ALEGCAST3.jpg",
    "stimulus/ANEWSBOX4.jpg",
    "stimulus/ASHOWCAP.jpg",
    "stimulus/Aashtray14.jpg",
    "stimulus/Afish57.jpg",
    "stimulus/Aflatwoodenba.jpg",
    "stimulus/Aflowerpot9.jpg",
    "stimulus/Agreenplastic.jpg",
    "stimulus/babyswig.jpg",
    "stimulus/gingerbreadcookie.jpg",
    "stimulus/ignitionkey01.jpg",
];
