var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/ACASKET5.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/ALAUNHAMP.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/8022302.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/Athermosand12.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/26428540.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/AHONEYJA2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/AHIGCHAIR.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/ADINROO16.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/ATAMBOURI.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/ABLUBLOTT.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACASKET5.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACPU2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AHONEYJA2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABLUBLOTT.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AMIXBOAR2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ADINROO16.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ALAUNHAMP.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aflowerwreat2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWALKTA25.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8022302.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26423175.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Alighter12.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Asantaclaus2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AHIGCHAIR.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26455183.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acork6.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Athermosand12.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ATAMBOURI.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AARROWS2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26428540.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/26423175.thl.jpg",
    "stimulus/26428540.thl.jpg",
    "stimulus/26455183.thl.jpg",
    "stimulus/8022302.thl.jpg",
    "stimulus/AARROWS2.jpg",
    "stimulus/ABLUBLOTT.jpg",
    "stimulus/ACASKET5.jpg",
    "stimulus/ACPU2.jpg",
    "stimulus/ADINROO16.jpg",
    "stimulus/AHIGCHAIR.jpg",
    "stimulus/AHONEYJA2.jpg",
    "stimulus/ALAUNHAMP.jpg",
    "stimulus/AMIXBOAR2.jpg",
    "stimulus/ATAMBOURI.jpg",
    "stimulus/AWALKTA25.jpg",
    "stimulus/Acork6.jpg",
    "stimulus/Aflowerwreat2.jpg",
    "stimulus/Alighter12.jpg",
    "stimulus/Asantaclaus2.jpg",
    "stimulus/Athermosand12.jpg",
];
