var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/ABOX8.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/26421106.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/ASMOKDE16.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/Aleatherpenc9.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/22911908.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/Aswitch17.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/AOTOSCOP5.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/26429137.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/Aflower136.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/Adolphin3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Apercussion16.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aflower136.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASMOKDE16.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aantiquecigar.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aleatherpenc9.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABOX8.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26429137.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/acquarium.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/22855236.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acrabwalking.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Adolphin3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Astingray2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/xqx00017.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABLACKNEC.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AOTOSCOP5.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8056402.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASTEPPER.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/22911908.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aswitch17.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26421106.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/22855236.thl.jpg",
    "stimulus/22911908.thl.jpg",
    "stimulus/26421106.thl.jpg",
    "stimulus/26429137.thl.jpg",
    "stimulus/8056402.thl.jpg",
    "stimulus/ABLACKNEC.jpg",
    "stimulus/ABOX8.jpg",
    "stimulus/AOTOSCOP5.jpg",
    "stimulus/ASMOKDE16.jpg",
    "stimulus/ASTEPPER.jpg",
    "stimulus/Aantiquecigar.jpg",
    "stimulus/Acrabwalking.jpg",
    "stimulus/Adolphin3.jpg",
    "stimulus/Aflower136.jpg",
    "stimulus/Aleatherpenc9.jpg",
    "stimulus/Apercussion16.jpg",
    "stimulus/Astingray2.jpg",
    "stimulus/Aswitch17.jpg",
    "stimulus/acquarium.jpg",
    "stimulus/xqx00017.jpg",
];
