var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/Afoodproces27.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/Agreenplastic.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/AHEATER.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/Abaggcon2.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/Aparrot80.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/Atoyseasaw.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/Aleatherbeltp.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/ABUILDI12.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/Acamcorde.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/Acablelatch.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agreenplastic.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26384637.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abackaccesso4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abaggcon2.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8026164.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aclamp58.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Afoodproces27.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aparrot80.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AHEATER.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABUILDI12.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acamcorde.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aleatherbeltp.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoyseasaw.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26379430.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/juicebox.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aplum11.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acablelatch.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoytractor17.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26431471.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Astroboscope5.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 20},
];

var practice_images = [
    "stimulus/26379430.thl.jpg",
    "stimulus/26384637.thl.jpg",
    "stimulus/26431471.thl.jpg",
    "stimulus/8026164.thl.jpg",
    "stimulus/ABUILDI12.jpg",
    "stimulus/AHEATER.jpg",
    "stimulus/Abackaccesso4.jpg",
    "stimulus/Abaggcon2.jpg",
    "stimulus/Acablelatch.jpg",
    "stimulus/Acamcorde.jpg",
    "stimulus/Aclamp58.jpg",
    "stimulus/Afoodproces27.jpg",
    "stimulus/Agreenplastic.jpg",
    "stimulus/Aleatherbeltp.jpg",
    "stimulus/Aparrot80.jpg",
    "stimulus/Aplum11.jpg",
    "stimulus/Astroboscope5.jpg",
    "stimulus/Atoyseasaw.jpg",
    "stimulus/Atoytractor17.jpg",
    "stimulus/juicebox.jpg",
];
