var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/8023968.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/AFULVOUST.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/Aavocado7.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/AWOODBIN.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/Atoybird10.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/26374899.thl.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/Acleaningbru3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/Aelectricgri3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/scooter.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/Abicycleodome.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aavocado7.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/9815480.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abicycleodome.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Aelectricgri3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AFULVOUST.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/DSCN6303-sm.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Astackingtoy2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/scooter.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWALKER11.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AGARBAGE.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AGLASSFL4.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26374899.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AMILPANS2.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acleaningbru3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoybird10.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWINEJUG3.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AWOODBIN.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/8023968.thl.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Ajacket12.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ABABYSPOO.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 20},
];

var practice_images = [
    "stimulus/26374899.thl.jpg",
    "stimulus/8023968.thl.jpg",
    "stimulus/9815480.thl.jpg",
    "stimulus/ABABYSPOO.jpg",
    "stimulus/AFULVOUST.jpg",
    "stimulus/AGARBAGE.jpg",
    "stimulus/AGLASSFL4.jpg",
    "stimulus/AMILPANS2.jpg",
    "stimulus/AWALKER11.jpg",
    "stimulus/AWINEJUG3.jpg",
    "stimulus/AWOODBIN.jpg",
    "stimulus/Aavocado7.jpg",
    "stimulus/Abicycleodome.jpg",
    "stimulus/Acleaningbru3.jpg",
    "stimulus/Aelectricgri3.jpg",
    "stimulus/Ajacket12.jpg",
    "stimulus/Astackingtoy2.jpg",
    "stimulus/Atoybird10.jpg",
    "stimulus/DSCN6303-sm.jpg",
    "stimulus/scooter.jpg",
];
