var practice_study_list = [
    {'block': 0, 'phase': 'study', 'trial': 1, 'stimulus': 'stimulus/ASPRITZER.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 2, 'stimulus': 'stimulus/APUPPY26.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 3, 'stimulus': 'stimulus/AMEDCONTA.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 4, 'stimulus': 'stimulus/Acandle120.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 5, 'stimulus': 'stimulus/AANTTRUCK.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 6, 'stimulus': 'stimulus/AJUG3.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 7, 'stimulus': 'stimulus/VMS7B.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 8, 'stimulus': 'stimulus/Abird5.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 9, 'stimulus': 'stimulus/AMINCOLLE.jpg', 'stim_type': 'old', 'correct_response': 'f'},
    {'block': 0, 'phase': 'study', 'trial': 10, 'stimulus': 'stimulus/ACREAME11.jpg', 'stim_type': 'old', 'correct_response': 'f'},
];

var practice_test_list = [
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AJUG3.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 1},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/VMS7B.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 2},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Atoy57.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 3},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ASPRITZER.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 4},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/hulahoop.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 5},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AANTTRUCK.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 6},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/underwear.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 7},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Afruitcake.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 8},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/APUPPY26.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 9},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/26427111.thl.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 10},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Agreenlighter.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 11},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/showercurtainsuchi.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 12},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Abird5.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 13},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Asaxophone.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 14},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Amonkey5.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 15},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AMINCOLLE.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 16},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/AMEDCONTA.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 17},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Awatch28.jpg', 'stim_type': 'new', 'correct_response': 'j', 'trial': 18},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/Acandle120.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 19},
    {'block': 0, 'phase': 'test', 'stimulus': 'stimulus/ACREAME11.jpg', 'stim_type': 'old', 'correct_response': 'f', 'trial': 20},
];

var practice_images = [
    "stimulus/26427111.thl.jpg",
    "stimulus/AANTTRUCK.jpg",
    "stimulus/ACREAME11.jpg",
    "stimulus/AJUG3.jpg",
    "stimulus/AMEDCONTA.jpg",
    "stimulus/AMINCOLLE.jpg",
    "stimulus/APUPPY26.jpg",
    "stimulus/ASPRITZER.jpg",
    "stimulus/Abird5.jpg",
    "stimulus/Acandle120.jpg",
    "stimulus/Afruitcake.jpg",
    "stimulus/Agreenlighter.jpg",
    "stimulus/Amonkey5.jpg",
    "stimulus/Asaxophone.jpg",
    "stimulus/Atoy57.jpg",
    "stimulus/Awatch28.jpg",
    "stimulus/VMS7B.jpg",
    "stimulus/hulahoop.jpg",
    "stimulus/showercurtainsuchi.jpg",
    "stimulus/underwear.jpg",
];
